In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [2]:
df=pd.read_csv("bank_Dataset for DT.csv ")

In [3]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,0,1,1,0,2343,1,0,2,5,8,1042,1,-1,0,3,1
1,56,0,1,1,0,45,0,0,2,5,8,1467,1,-1,0,3,1
2,41,9,1,1,0,1270,1,0,2,5,8,1389,1,-1,0,3,1
3,55,7,1,1,0,2476,1,0,2,5,8,579,1,-1,0,3,1
4,54,0,1,2,0,184,0,0,2,5,8,673,2,-1,0,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,1,2,0,0,1,1,0,0,20,0,257,1,-1,0,3,0
11158,39,7,1,1,0,733,0,0,2,16,6,83,4,-1,0,3,0
11159,32,9,2,1,0,29,0,0,0,19,1,156,2,-1,0,3,0
11160,43,9,1,1,0,0,0,1,0,8,8,9,2,172,5,0,0
11161,34,9,1,1,0,0,0,0,0,9,5,628,1,-1,0,3,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  int64
 2   marital    11162 non-null  int64
 3   education  11162 non-null  int64
 4   default    11162 non-null  int64
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  int64
 7   loan       11162 non-null  int64
 8   contact    11162 non-null  int64
 9   day        11162 non-null  int64
 10  month      11162 non-null  int64
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  int64
 16  deposit    11162 non-null  int64
dtypes: int64(17)
memory usage: 1.4 MB

In [5]:
#separation of x and y

x=df.iloc[:,:-1]
y=df["deposit"]

In [6]:
x

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,59,0,1,1,0,2343,1,0,2,5,8,1042,1,-1,0,3
1,56,0,1,1,0,45,0,0,2,5,8,1467,1,-1,0,3
2,41,9,1,1,0,1270,1,0,2,5,8,1389,1,-1,0,3
3,55,7,1,1,0,2476,1,0,2,5,8,579,1,-1,0,3
4,54,0,1,2,0,184,0,0,2,5,8,673,2,-1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,1,2,0,0,1,1,0,0,20,0,257,1,-1,0,3
11158,39,7,1,1,0,733,0,0,2,16,6,83,4,-1,0,3
11159,32,9,2,1,0,29,0,0,0,19,1,156,2,-1,0,3
11160,43,9,1,1,0,0,0,1,0,8,8,9,2,172,5,0
11161,34,9,1,1,0,0,0,0,0,9,5,628,1,-1,0,3

In [7]:
y

0        1
1        1
2        1
3        1
4        1
        ..
11157    0
11158    0
11159    0
11160    0
11161    0
Name: deposit, Length: 11162, dtype: int64

In [8]:
df['deposit'].value_counts()

deposit
0    5873
1    5289
Name: count, dtype: int64

In [9]:

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30,random_state=42)

In [10]:
lr=LogisticRegression()    #create two object lr and dt
#svc=SVC()
dt=DecisionTreeClassifier()

In [11]:
#calling all function

def mymodel(m):
    m.fit(xtrain,ytrain)
    ypred=m.predict(xtest)
    ac=accuracy_score(ytest,ypred)
    cr=classification_report(ytest,ypred)
    print(f"Accuracy:  {ac} \n \n Classification Report: \n {cr}")

In [12]:
mymodel(lr)

Accuracy:  0.7476858763810093

 Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.80      0.77      1742
           1       0.76      0.69      0.72      1607

    accuracy                           0.75      3349
   macro avg       0.75      0.75      0.75      3349
weighted avg       0.75      0.75      0.75      3349

In [13]:
mymodel(dt)

Accuracy:  0.7790385189608838

 Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.79      0.79      1742
           1       0.77      0.76      0.77      1607

    accuracy                           0.78      3349
   macro avg       0.78      0.78      0.78      3349
weighted avg       0.78      0.78      0.78      3349

In [14]:
#to check model overfitiing ahe ka
dt.score(xtrain,ytrain)  #testing score should be more  so this is overfitting problem

1.0

In [15]:
dt.score(xtest,ytest)

0.7790385189608838

In [16]:
#hypertuning in DT ....1.max_depth
acc_list=[]
depth_list=[]
for i in range(1,16):
    dt1=DecisionTreeClassifier(max_depth=i)
    dt1.fit(xtrain,ytrain)
    ypred=dt1.predict(xtest)
    ac=accuracy_score(ytest,ypred)

    depth_list.append(i)
    acc_list.append(ac)

    print(f"For max_depth={i}  We get Accuracy= {ac}")

For max_depth=1  We get Accuracy= 0.7106598984771574
For max_depth=2  We get Accuracy= 0.7055837563451777
For max_depth=3  We get Accuracy= 0.775753956404897
For max_depth=4  We get Accuracy= 0.7814272917288743
For max_depth=5  We get Accuracy= 0.8038220364287847
For max_depth=6  We get Accuracy= 0.8056136160047775
For max_depth=7  We get Accuracy= 0.8148701104807405
For max_depth=8  We get Accuracy= 0.8112869513287548
For max_depth=9  We get Accuracy= 0.80501642281278
For max_depth=10  We get Accuracy= 0.8053150194087787
For max_depth=11  We get Accuracy= 0.8091967751567632
For max_depth=12  We get Accuracy= 0.8032248432367871
For max_depth=13  We get Accuracy= 0.7966557181248134
For max_depth=14  We get Accuracy= 0.7933711555688265
For max_depth=15  We get Accuracy= 0.7945655419528217

In [18]:
dt2=DecisionTreeClassifier(max_depth=7)
mymodel(dt2)

Accuracy:  0.8154673036727381

 Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.87      0.83      1742
           1       0.84      0.76      0.80      1607

    accuracy                           0.82      3349
   macro avg       0.82      0.81      0.81      3349
weighted avg       0.82      0.82      0.81      3349

In [ ]:
dt2.score(xtrain,ytrain)

In [ ]:
#hypertuning in DT ....2.min_sample_split
acc_list=[]
n_sample_split_list=[]
for i in range(1,50):
    dt3=DecisionTreeClassifier(min_samples_split=2)
    dt3.fit(xtrain,ytrain)
    ypred=dt3.predict(xtest)
    ac=accuracy_score(ytest,ypred)

    n_sample_split_list.append(i)
    acc_list.append(ac)

    print(f"For max_depth={i}  We get Accuracy= {ac}")

In [21]:
dt4=DecisionTreeClassifier(max_depth=48)
mymodel(dt4)

Accuracy:  0.7853090474768588

 Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.80      0.79      1742
           1       0.78      0.77      0.78      1607

    accuracy                           0.79      3349
   macro avg       0.78      0.78      0.78      3349
weighted avg       0.79      0.79      0.79      3349

In [23]:
#hypertuning in DT ....2.min_sample_leaf
acc_list=[]
min_sample_leaf_list=[]
for i in range(1,50):
    dt5=DecisionTreeClassifier(min_samples_leaf=i)
    dt5.fit(xtrain,ytrain)
    ypred=dt5.predict(xtest)
    ac=accuracy_score(ytest,ypred)

    min_sample_leaf_list.append(i)
    acc_list.append(ac)

    print(f"For min_sample_leaf={i}  We get Accuracy= {ac}")

For min_sample_leaf=1  We get Accuracy= 0.7838160644968647
For min_sample_leaf=2  We get Accuracy= 0.782024484920872
For min_sample_leaf=3  We get Accuracy= 0.7930725589728277
For min_sample_leaf=4  We get Accuracy= 0.794266945356823
For min_sample_leaf=5  We get Accuracy= 0.7939683487608241
For min_sample_leaf=6  We get Accuracy= 0.7939683487608241
For min_sample_leaf=7  We get Accuracy= 0.7999402806808003
For min_sample_leaf=8  We get Accuracy= 0.7999402806808003
For min_sample_leaf=9  We get Accuracy= 0.8068080023887728
For min_sample_leaf=10  We get Accuracy= 0.8139743206927441
For min_sample_leaf=11  We get Accuracy= 0.8154673036727381
For min_sample_leaf=12  We get Accuracy= 0.8169602866527321
For min_sample_leaf=13  We get Accuracy= 0.8178560764407286
For min_sample_leaf=14  We get Accuracy= 0.8238280083607047
For min_sample_leaf=15  We get Accuracy= 0.8262167811286951
For min_sample_leaf=16  We get Accuracy= 0.826515377724694
For min_sample_leaf=17  We get Accuracy= 0.8277097641086891
For min_sample_leaf=18  We get Accuracy= 0.8262167811286951
For min_sample_leaf=19  We get Accuracy= 0.8274111675126904
For min_sample_leaf=20  We get Accuracy= 0.8289041504926844
For min_sample_leaf=21  We get Accuracy= 0.8289041504926844
For min_sample_leaf=22  We get Accuracy= 0.8300985368766796
For min_sample_leaf=23  We get Accuracy= 0.8336816960286653
For min_sample_leaf=24  We get Accuracy= 0.8336816960286653
For min_sample_leaf=25  We get Accuracy= 0.8336816960286653
For min_sample_leaf=26  We get Accuracy= 0.8330845028366677
For min_sample_leaf=27  We get Accuracy= 0.828008360704688
For min_sample_leaf=28  We get Accuracy= 0.8330845028366677
For min_sample_leaf=29  We get Accuracy= 0.8324873096446701
For min_sample_leaf=30  We get Accuracy= 0.8315915198566737
For min_sample_leaf=31  We get Accuracy= 0.8351746790086593
For min_sample_leaf=32  We get Accuracy= 0.8303971334726784
For min_sample_leaf=33  We get Accuracy= 0.8300985368766796
For min_sample_leaf=34  We get Accuracy= 0.8321887130486713
For min_sample_leaf=35  We get Accuracy= 0.8345774858166617
For min_sample_leaf=36  We get Accuracy= 0.8318901164526724
For min_sample_leaf=37  We get Accuracy= 0.8315915198566737
For min_sample_leaf=38  We get Accuracy= 0.8300985368766796
For min_sample_leaf=39  We get Accuracy= 0.8351746790086593
For min_sample_leaf=40  We get Accuracy= 0.8351746790086593
For min_sample_leaf=41  We get Accuracy= 0.8345774858166617
For min_sample_leaf=42  We get Accuracy= 0.8297999402806808
For min_sample_leaf=43  We get Accuracy= 0.8297999402806808
For min_sample_leaf=44  We get Accuracy= 0.8289041504926844
For min_sample_leaf=45  We get Accuracy= 0.8303971334726784
For min_sample_leaf=46  We get Accuracy= 0.8292027470886831
For min_sample_leaf=47  We get Accuracy= 0.8277097641086891
For min_sample_leaf=48  We get Accuracy= 0.8277097641086891
For min_sample_leaf=49  We get Accuracy= 0.8286055538966856

In [25]:
dt6=DecisionTreeClassifier(min_samples_leaf=40)
mymodel(dt6)

Accuracy:  0.8351746790086593

 Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.81      0.84      1742
           1       0.81      0.86      0.83      1607

    accuracy                           0.84      3349
   macro avg       0.84      0.84      0.84      3349
weighted avg       0.84      0.84      0.84      3349

In [26]:
dt6.score(xtrain,ytrain)

0.8462818379623704